[database]
server = "127.0.0.1" # Mysql Database Server
port = "3306" # Mysql Database Port
database = "tinytik" # Mysql Database Name
user = "root" # Mysql Database User
password = "" # Mysql Database Password
debug = true # Mysql Database Debug

[app]
name = "TinyTik" # Application Name
description = "TinyTik API"
host = "0.0.0.0:1010" # Application Port And IP
proxy = "" # Outgoing Proxy
environment = "development" # development,production

[redis]
connectionString = "127.0.0.1:6379"

[kafka]
ip = "" # Kafka IP ( ignored if empty, eg. 0.0.0.0 )
port = "" # Kafka Port ( ignored if empty, eg. 9092 )
topic = "" # Kafka Default Topic To Publish ( ignored if empty, eg. Test )