[database]
server = "127.0.0.1" # Mysql Database Server
port = "3306" # Mysql Database Port
database = "take10dashboardFull" # Mysql Database Name
user = "root" # Mysql Database User
password = "root" # Mysql Database Password
debug = true # Mysql Database Debug

[app]
name = "Take10Dashboard" # Application Name
description = "Take10Triva Dashboard API"
host = "0.0.0.0:8080" # Application Port And IP
proxy = "" # Outgoing Proxy
environment = "development" # development,production

[kafka]
ip = "" # Kafka IP ( ignored if empty, eg. 0.0.0.0 )
port = "" # Kafka Port ( ignored if empty, eg. 9092 )
topic = "" # Kafka Default Topic To Publish ( ignored if empty, eg. Test )